### ISSUE TITLE
Thermal throttling causes misreads, disconnects

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#10]
When GPU temp > 85* C, We have been observing a pattern of issues, but not 100% sure about this.

**Comment by ajaygautam** [comment]
The offer of returning the PCs still on the table.

**Comment by jktrackman** [comment]
duplicate of ticket #6 

Should be fixed having the PC's out of the original PC cabinets

**Comment by ajaygautam** [comment]
Thanks JK.
