### ISSUE TITLE
"Normalization" should apply to Virtual Golf too

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#21]
Currently... "Normalization" is applicable to TPS only, not Virtual Golf.

**Comment by ajbtrackman** [comment]
Bringing normalization to VG is not currently in the pipeline as the dev team is focused on determining and fixing the root causes for any distance discrepancies. This is ongoing and extremely high priority.

**Comment by ajaygautam** [comment]
Well, as long as the distances show up right, this specific feature is not required.
