### ISSUE TITLE
Incorrect firmness setting displayed

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#26]
Firmness setting
@Support We noticed that when you choose the fairway firmness setting prior to entering play, it does not match up when you are on course. Specifically, we chose “hard” but when you go into settings on course it is set to “soft”. This is happening in both VG rounds and On Course Practice.

**Comment by jktrackman** [comment]
Should be fixed in 6.3.56

**Comment by ajbtrackman** [comment]
To be fixed in next SW service release - target late January
