### ISSUE TITLE
Putting in scramble format - No way to "mark-ball"

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#30]
Putting - Scramble
Person 1 hit Putt short. 
Person 2 hits same line. 
Person 2’s ball hits person 1’s ball. 
2’s ball stops. 
1’s ball moves forward.

**Comment by jktrackman** [comment]
Fixed in 6.3.56

**Comment by ajbtrackman** [comment]
To be fixed in next SW service release - target late January
