### ISSUE TITLE
Can't continue game after replay on scramble play 2nd shot

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#32]
Bug:
Setup 2-player scramble:
Player 1 hits
Player 2 hits
On the shot summary screen, select “replay”. 
After watching replay, select Done. 
Observe - no way to just continue the round. Player 2 is forced to select Mulligan, rehit, pickup. 
Versions:

TPS App | 6.3.56
-- | --
Sensor | 2.6.626
Hardware | 2.6.37
Video | 4.6.20
Reports | 1.2120
Virtual Golf | 1.0.388
TM4 | 1835-4102
Sr # | 18354012
Firmware | 1.7.4-beta.1
Bootloader | 6.03

**Comment by jktrackman** [comment]
reported to DK development team
