### ISSUE TITLE
Wood distances are LOW for slow swing speeds

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#4]
For people with swing speeds of 70 to 90, wood distances are read lower!

**Comment by ajaygautam** [comment]
Launch angle issue with virtual golf impacting slow swing speed driver distances.
TM does not provide correct value in time for VG to render.
No "boost" available either

**Comment by ajaygautam** [comment]
When comparing averages in Shot Analysis vs. VG, it seems we are getting 10-15 yds shorter carry (and subsequent total) in VG.
Please note, something to look into specifically is it seems to only happen with slower swing speeds/higher handicaps. Higher speed players do not have the same discrepancy…

**Comment by ajaygautam** [comment]
Reads are approx. (10%) less between range and course

**Comment by jktrackman** [comment]
Distances should be much closer in 6.3.56 - note that numbers will be slightly different in TPS due to environmental differences on course

**Comment by ajaygautam** [comment]
Did testing on St Andrews Old course.
Distance are better, but not "much closer".
About "environmental differences" - I don't think thats right - irons don't have this issue, and wedges (still) have the reverse issue - wedge distances are way longer!
