### ISSUE TITLE
Thermal Throttling - Is Unity 3D engine too much for these hardware specs?

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#6]
We can't cool the (stock) GPU! The longer the round plays, the more choppiness we get.
After our optimal fan settings, the first 9 holes are pretty much smooth-as-butter!
Choppiness starts around hole 12, and gets worst through the rest of round!

Yes - TPS does not use much CPU/GPU.
Its the Virtual Golf software that uses GPU "a LOT"!!
Wonder is there are any best practices we are missing for VIrtual Golf / the-3d-engine.

**Comment by jktrackman** [comment]
No longer an issue correct? Due to PC cabinet?

**Comment by ajaygautam** [comment]
Thanks for sending us the new PCs. Its better now.
We are closing this issue.
