### ISSUE TITLE
TPS - unable to delete shot data from Combine and/or Practice

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#9]
For obvious mis-reads!

**Comment by ajaygautam** [comment]
Example: John was doing shot practice with PW, and TM read 165!
No way John hits 165 with his PW.
I (Ajay) was standing there. It was a well hit shot.
The misread messed up his score.
Player feeling - demotivated, disappointed.

**Comment by jktrackman** [comment]
We are unable to delete shots from combine

You are able to delete shots if you are just practicing in TPS

You right click the shot on the shot list and then click delete
